[workspace]
channels = ["conda-forge"]
name = "simulation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
download = "python 00/squidle_dataset.py"

[dependencies]
python = "*"
numpy = "*"
matplotlib = "*"
scipy = "*"
opencv = "*"
libopencv = ">=4.8"
pandas = "*"
tqdm = "*"
requests = "*"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
pycolmap = "*"