[workspace]
channels = ["conda-forge"]
name = "simulation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
remove-refraction = "python remove_refraction.py"
visualise-refraction = "python visualise_refraction.py"
find-best-scale = "python find_best_scale.py"

[dependencies]
python = "*"
numpy = "*"
matplotlib = "*"
scipy = "*"
opencv = "*"
libopencv = ">=4.8"
pandas = "*"
tqdm = "*"
requests = "*"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
pycolmap = "*"